name: 'Pull Request'

on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  validate:
    name: 'Build & Lint'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Build
        working-directory: .
        run: |
          npm ci
          npm run build
          npm run lint
        shell: bash
